import { v4 as uuidv4 } from 'uuid';

// Kids
import k1 from '../asset/kids/image-kids-1.png';
import k13 from '../asset/kids/image-kids-13.png';
import k14 from '../asset/kids/image-kids-14.png';
import k16 from '../asset/kids/image-kids-16.png';
import k17 from '../asset/kids/image-kids-17.png';
import k2 from '../asset/kids/image-kids-2.png';
import k21 from '../asset/kids/image-kids-21.png';
import k3 from '../asset/kids/image-kids-3.png';
import k4 from '../asset/kids/image-kids-4.png';
import k5 from '../asset/kids/image-kids-5.png';
import k9 from '../asset/kids/image-kids-9.png';

// Men
import m10 from '../asset/men/image-men-10.png';
import m11 from '../asset/men/image-men-11.png';
import m13 from '../asset/men/image-men-13.png';
import m15 from '../asset/men/image-men-15.png';
import m17 from '../asset/men/image-men-17.png';
import m18 from '../asset/men/image-men-18.png';
import m20 from '../asset/men/image-men-20.png';
import m22 from '../asset/men/image-men-22.png';
import m23 from '../asset/men/image-men-23.png';
import m24 from '../asset/men/image-men-24.png';
import m25 from '../asset/men/image-men-25.png';
import m26 from '../asset/men/image-men-26.png';
import m28 from '../asset/men/image-men-28.png';
import m29 from '../asset/men/image-men-29.png';
import m30 from '../asset/men/image-men-30.png';
import m4 from '../asset/men/image-men-4.png';
import m5 from '../asset/men/image-men-5.png';
import m7 from '../asset/men/image-men-7.png';
import m8 from '../asset/men/image-men-8.png';

// women
import w1 from '../asset/women/image-women-1.png';
import w10 from '../asset/women/image-women-10.png';
import w14 from '../asset/women/image-women-14.png';
import w15 from '../asset/women/image-women-15.png';
import w16 from '../asset/women/image-women-16.png';
import w18 from '../asset/women/image-women-18.png';
import w2 from '../asset/women/image-women-2.png';
import w22 from '../asset/women/image-women-22.png';

const productData = [
  {
    id: uuidv4(),
    img: k1,
    name: 'TRIUMPH ELITE',
    rating: '4.3',
    review: '132 reviews',
    original_price: '$1499',
    discounted_price: '$999',
    category_name: 'kid',
    is_stock: 'Out of stock',
  },
  {
    id: uuidv4(),
    img: m10,
    name: 'HARMONY XCEL',
    rating: '4.2',
    review: '987 reviews',
    original_price: '$1199',
    discounted_price: '$1099',
    category_name: 'men',
  },
  {
    id: uuidv4(),
    img: w1,
    name: 'INNOVATE PRECISION X',
    rating: '3',
    review: '78 reviews',
    original_price: '$1599',
    discounted_price: '$1499',
    category_name: 'women',
    is_stock: 'Out of stock',
    trending: 'Trending',
  },
  {
    id: uuidv4(),
    img: m11,
    name: 'ASCEND VELOCITY',
    rating: '2.4',
    review: '9 reviews',
    original_price: '$1999',
    discounted_price: '$1899',
    category_name: 'men',
    trending: 'Trending',
  },
  {
    id: uuidv4(),
    img: w10,
    name: 'CATALYST APEX X',
    rating: '4.9',
    review: '65 reviews',
    original_price: '$1299',
    discounted_price: '1199',
    category_name: 'women',
  },
  {
    id: uuidv4(),
    img: m13,
    name: 'EVOLVE PRO X',
    rating: '5',
    review: '132 reviews',
    original_price: '$699',
    discounted_price: '$599',
    category_name: 'men',
    trending: 'Trending',
  },
  {
    id: uuidv4(),
    img: m15,
    name: 'VELOCITY MOMENTUM X',
    rating: '4.5',
    review: '56 reviews',
    original_price: '$499',
    discounted_price: '$399',
    category_name: 'men',
    is_stock: 'Out of stock',
  },
  {
    id: uuidv4(),
    img: w14,
    name: 'OPTIMUM ELITE',
    rating: '4.8',
    review: '1609 reviews',
    original_price: '$599',
    discounted_price: '$499',
    category_name: 'women',
  },
  {
    id: uuidv4(),
    img: m17,
    name: 'CATALYST HYPERION',
    rating: '4.8',
    review: '89 reviews',
    original_price: '$1699',
    discounted_price: '$1599',
    category_name: 'men',
  },
  {
    id: uuidv4(),
    img: m18,
    name: 'INNOVATE OPTIMA',
    rating: '4.8',
    review: '654 reviews',
    original_price: '$299',
    discounted_price: '$199',
    category_name: 'men',
    is_stock: 'Out of stock',
    trending: 'Trending',
  },
  {
    id: uuidv4(),
    img: m20,
    name: 'VANGUARD ACCELERATE',
    rating: '1.6',
    review: '43 reviews',
    original_price: '$1899',
    discounted_price: '1799',
    category_name: 'men',
  },
  {
    id: uuidv4(),
    img: w15,
    name: 'EMPOWER CATALYST',
    rating: '4.3',
    review: '109 reviews',
    original_price: '$149',
    discounted_price: '$99',
    category_name: 'women',
  },
  {
    id: uuidv4(),
    img: m22,
    name: 'ELEVATION DYNAMO X',
    rating: '3.7',
    review: '457 reviews',
    original_price: '$1099',
    discounted_price: '$999',
    category_name: 'men',
  },
  {
    id: uuidv4(),
    img: k13,
    name: 'EQUINOX MAXIMA',
    rating: '4.5',
    review: '109 reviews',
    original_price: '$399',
    discounted_price: '$299',
    category_name: 'kid',
  },
  {
    id: uuidv4(),
    img: m23,
    name: 'MOMENTUM BOOST',
    rating: '3.5',
    review: '123 reviews',
    original_price: '$799',
    discounted_price: '$699',
    category_name: 'men',
  },
  {
    id: uuidv4(),
    img: w16,
    name: 'FUSION QUANTUM',
    rating: '4.6',
    review: '765 reviews',
    original_price: '$1799',
    discounted_price: '$1699',
    category_name: 'women',
  },
  {
    id: uuidv4(),
    img: m24,
    name: 'SURGE PRO X',
    rating: '4.8',
    review: '78 reviews',
    original_price: '$599',
    discounted_price: '$499',
    category_name: 'men',
  },
  {
    id: uuidv4(),
    img: w18,
    name: 'AETHER ELEVATION',
    rating: '4.5',
    review: '22 reviews',
    original_price: '$1099',
    discounted_price: '$999',
    category_name: 'women',
  },
  {
    id: uuidv4(),
    img: m25,
    name: 'SYNTHESIS OPTIMUM',
    rating: '4.1',
    review: '345 reviews',
    original_price: '$99',
    discounted_price: '$89',
    category_name: 'men',
    is_stock: 'Out of stock',
  },
  {
    id: uuidv4(),
    img: w2,
    name: 'FUSION EQUINOX',
    rating: '4',
    review: '36 reviews',
    original_price: '$1299',
    discounted_price: '$1199',
    category_name: 'women',
  },
  {
    id: uuidv4(),
    img: m26,
    name: 'QUANTUM VELOCITY',
    rating: '3.8',
    review: '432 reviews',
    original_price: '$1499',
    discounted_price: '$1399',
    category_name: 'men',
    trending: 'Trending',
  },
  {
    id: uuidv4(),
    img: w22,
    name: 'ZENITH ASCEND',
    rating: '3.5',
    review: '34 reviews',
    original_price: '$159',
    discounted_price: '$99',
    category_name: 'women',
  },
  {
    id: uuidv4(),
    img: k14,
    name: 'PRECISION STELLAR X',
    rating: '4.3',
    review: '69 reviews',
    original_price: '$399',
    discounted_price: '$299',
    category_name: 'kid',
    is_stock: 'Out of stock',
    trending: 'Trending',
  },
  {
    id: uuidv4(),
    img: m28,
    name: 'APEX QUANTUM X',
    rating: '3.2',
    review: '777 reviews',
    original_price: '$1499',
    discounted_price: '$999',
    category_name: 'men',
    is_stock: 'Out of stock',
  },
  {
    id: uuidv4(),
    img: k16,
    name: 'ELEVATION ULTRA',
    rating: '4.5',
    review: '166 reviews',
    original_price: '$699',
    discounted_price: '$599',
    category_name: 'kid',
    is_stock: 'Out of stock',
  },
  {
    id: uuidv4(),
    img: k17,
    name: 'IGNITE PRO X',
    rating: '3.3',
    review: '200 reviews',
    original_price: '$399',
    discounted_price: '$299',
    category_name: 'kid',
  },
  {
    id: uuidv4(),
    img: m29,
    name: 'DYNAMO STRIDE',
    rating: '4.3',
    review: '89 reviews',
    original_price: '$199',
    discounted_price: '$99',
    category_name: 'men',
    is_stock: 'Out of stock',
    trending: 'Trending',
  },
  {
    id: uuidv4(),
    img: k2,
    name: 'DYNAMO STRIDE',
    rating: '4.9',
    review: '398 reviews',
    original_price: '$1299',
    discounted_price: '$1199',
    category_name: 'kid',
    is_stock: 'Out of stock',
  },
  {
    id: uuidv4(),
    img: k21,
    name: 'PRECISION OPTIMA',
    rating: '3.4',
    review: '39 reviews',
    original_price: '$99',
    discounted_price: '$89',
    category_name: 'kid',
  },
  {
    id: uuidv4(),
    img: m30,
    name: 'NOVA IGNITION',
    rating: '2.5',
    review: '54 reviews',
    original_price: '$1499',
    discounted_price: '13599',
    category_name: 'men',
  },
  {
    id: uuidv4(),
    img: m4,
    name: 'LUMINARY SYNTHESIS',
    rating: '4.8',
    review: '322 reviews',
    original_price: '$699',
    discounted_price: '$599',
    category_name: 'men',
  },
  {
    id: uuidv4(),
    img: m5,
    name: 'VELOCITY QUANTUM',
    rating: '4.9',
    review: '555 reviews',
    original_price: '$2099',
    discounted_price: '$1999',
    category_name: 'men',
  },
  {
    id: uuidv4(),
    img: m7,
    name: 'TURBO IMPACT',
    rating: '3.5',
    review: '43 reviews',
    original_price: '$1499',
    discounted_price: '$999',
    category_name: 'men',
  },
  {
    id: uuidv4(),
    img: k3,
    name: 'OPTIMUM STRIDE',
    rating: '4.3',
    review: '144 reviews',
    original_price: '$399',
    discounted_price: '$299',
    category_name: 'kid',
  },
  {
    id: uuidv4(),
    img: k4,
    name: 'AETHER ULTRA',
    rating: '2.3',
    review: '23 reviews',
    original_price: '$999',
    discounted_price: '$899',
    category_name: 'kid',
    is_stock: 'Out of stock',
    trending: 'Trending',
  },
  {
    id: uuidv4(),
    img: m8,
    name: 'SURGE OPTIMUM',
    rating: '3.9',
    review: '43 reviews',
    original_price: '$199',
    discounted_price: '$99',
    category_name: 'men',
    trending: 'Trending',
  },
  {
    id: uuidv4(),
    img: k5,
    name: 'FUSION ELEMENT',
    rating: '4.4',
    review: '19 reviews',
    original_price: '$79',
    discounted_price: '$69',
    category_name: 'kid',
  },
  {
    id: uuidv4(),
    img: k9,
    name: 'VELOCITY BOOST',
    rating: '3.1',
    review: '29 reviews',
    original_price: '$699',
    discounted_price: '$599',
    category_name: 'kid',
    is_stock: 'Out of stock',
    trending: 'Trending',
  },
];

export default productData;
